require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '16.6'
use_frameworks!

target 'FlareLaneExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-flarelane', :path => '../..'
end

target 'FlareLaneNotificationServiceExtension' do
  pod 'FlareLane', '1.10.0'
end